openapi: 3.1.0
info:
  description: "This is the OpenAPI Spec for the [Loops API](https://loops.so/docs/api)."
  title: Loops OpenAPI Spec
  version: 1.4.1
servers:
- url: https://app.loops.so/api/v1
tags:
- name: API key
- description: Manage contacts in your audience
  name: Contacts
- description: Manage contact properties
  name: Contact properties
- description: View mailing lists
  name: Mailing lists
- description: Trigger email sending with events
  name: Events
- description: Send and view transactional emails
  name: Transactional emails
paths:
  /api-key:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_api_key_get_200_response'
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_api_key_get_401_response'
          description: Invalid API key
      security:
      - apiKey: []
      summary: Test your API key
      tags:
      - API key
  /contacts/create:
    post:
      description: Add a contact to your audience.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactRequest'
        description: "You can add custom contact properties as keys in this request\
          \ (of type `string`, `number`, `boolean` or `date` ([see available date\
          \ formats](https://loops.so/docs/contacts/properties#dates))).<br>Make sure\
          \ to create the properties in Loops before using them in API calls."
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactSuccessResponse'
          description: Successful create.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactFailureResponse'
          description: Bad request (e.g. invalid email address).
        "405":
          description: Wrong HTTP request method.
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactFailureResponse'
          description: Email or `userId` already exists.
      security:
      - apiKey: []
      summary: Create a contact
      tags:
      - Contacts
  /contacts/update:
    put:
      description: "Update a contact by `email` or `userId`.<br>If you want to update\
        \ a contactâ€™s email address, the contact will first need a `userId` value.\
        \ You can then make a request containing the userId field along with an updated\
        \ email address."
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactRequest'
        description: "You can add custom contact properties as keys in this request\
          \ (of type `string`, `number`, `boolean` or `date` ([see available date\
          \ formats](https://loops.so/docs/contacts/properties#dates))).<br>Make sure\
          \ to create the properties in Loops before using them in API calls."
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactSuccessResponse'
          description: Successful update.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactFailureResponse'
          description: Bad request (e.g. `email` or `userId` are missing).
        "405":
          description: Wrong HTTP request method.
      security:
      - apiKey: []
      summary: Update a contact
      tags:
      - Contacts
  /contacts/find:
    get:
      description: Search for a contact by `email` or `userId`. Only one parameter
        is allowed.
      parameters:
      - description: Email address (URI-encoded)
        explode: true
        in: query
        name: email
        required: false
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: userId
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Contact'
                type: array
          description: List of contacts (or an empty array if no contact was found).
            Contact objects will include any custom properties.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactFailureResponse'
          description: Bad request (e.g. invalid email address).
        "405":
          description: Wrong HTTP request method.
      security:
      - apiKey: []
      summary: Find a contact
      tags:
      - Contacts
  /contacts/delete:
    post:
      description: Delete a contact by `email` or `userId`.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactDeleteRequest'
        description: Include only one of `email` or `userId`.
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactDeleteResponse'
          description: Successful delete.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactFailureResponse'
          description: Bad request (e.g. `email` and `userId` are both provided).
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactFailureResponse'
          description: Contact not found.
        "405":
          description: Wrong HTTP request method.
      security:
      - apiKey: []
      summary: Delete a contact
      tags:
      - Contacts
  /contacts/properties:
    get:
      description: Retrieve a list of your account's contact properties.<br>Use the
        `list` parameter to query "all" or "custom" properties.
      parameters:
      - description: \"all\" (default) or \"custom\"
        explode: true
        in: query
        name: list
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ContactProperty'
                type: array
          description: Successful.
        "405":
          description: Wrong HTTP request method.
      security:
      - apiKey: []
      summary: Get a list of contact properties
      tags:
      - Contact properties
    post:
      description: Add a contact property to your team.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactPropertyCreateRequest'
        description: "The name value must be in camelCase, like `planName`."
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactPropertySuccessResponse'
          description: Successful create.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactPropertyFailureResponse'
          description: Bad request (e.g. invalid type).
        "405":
          description: Wrong HTTP request method.
      security:
      - apiKey: []
      summary: Create a contact property
      tags:
      - Contact properties
  /lists:
    get:
      description: Retrieve a list of your account's mailing lists.
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/MailingList'
                type: array
          description: Successful.
        "405":
          description: Wrong HTTP request method.
      security:
      - apiKey: []
      summary: Get a list of mailing lists
      tags:
      - Mailing lists
  /events/send:
    post:
      description: Send events to trigger emails in Loops.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventRequest'
        description: "Provide either `email` or `userId` to identify the contact ([read\
          \ more](https://loops.so/docs/api-reference/send-event#body)).<br>You can\
          \ add event properties, which will be available in emails sent by this event.\
          \ Values can be of type string, number, boolean or date ([see allowed date\
          \ formats](https://loops.so/docs/events/properties#important-information-about-event-properties)).<br>Make\
          \ sure to create the properties in Loops before using them in API calls.<br>You\
          \ can add contact properties as keys in this request (of type `string`,\
          \ `number`, `boolean` or `date` ([see available date formats](https://loops.so/docs/contacts/properties#dates)))."
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventSuccessResponse'
          description: Successful send.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventFailureResponse'
          description: Bad request (e.g. `eventName` is missing).
        "405":
          description: Wrong HTTP request method.
      security:
      - apiKey: []
      summary: Send an event
      tags:
      - Events
  /transactional:
    get:
      description: Get a list of published transactional emails.
      parameters:
      - description: How many results to return in each request. Must be between 10
          and 50. Default is 20.
        explode: true
        in: query
        name: perPage
        required: false
        schema:
          type: string
        style: form
      - description: "A cursor, to return a specific page of results. Cursors can\
          \ be found from the `pagination.nextCursor` value in each response."
        explode: true
        in: query
        name: cursor
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/TransactionalEmail'
                type: array
          description: Successful.
        "405":
          description: Wrong HTTP request method.
      security:
      - apiKey: []
      summary: List transactional emails
      tags:
      - Transactional emails
    post:
      description: "Send a transactional email to a contact.<br>Please [email us](mailto:help@loops.so)\
        \ to enable attachments on your account before using them with the API."
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionalRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionalSuccessResponse'
          description: Successful send.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_transactional_post_400_response'
          description: Bad request (e.g. transactional email is not published).
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionalFailure2Response'
          description: Transactional email not found.
        "405":
          description: Wrong HTTP request method.
      security:
      - apiKey: []
      summary: Send a transactional email
      tags:
      - Transactional emails
components:
  schemas:
    Contact:
      example:
        firstName: firstName
        lastName: lastName
        subscribed: true
        id: id
        source: source
        userGroup: userGroup
        userId: userId
        email: email
        mailingLists: "{}"
      properties:
        id:
          type: string
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        source:
          type: string
        subscribed:
          type: boolean
        userGroup:
          type: string
        userId:
          type: string
        mailingLists:
          description: An object of mailing list IDs and boolean subscription statuses.
          type: object
    ContactRequest:
      example:
        firstName: firstName
        lastName: lastName
        subscribed: true
        userGroup: userGroup
        userId: userId
        email: email
        mailingLists: "{}"
      properties:
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        subscribed:
          type: boolean
        userGroup:
          type: string
        userId:
          type: string
        mailingLists:
          description: An object of mailing list IDs and boolean subscription statuses.
          type: object
      required:
      - email
    ContactSuccessResponse:
      example:
        success: true
        id: id
      properties:
        success:
          type: boolean
        id:
          type: string
      required:
      - id
      - success
    ContactFailureResponse:
      example:
        success: true
        message: message
      properties:
        success:
          type: boolean
        message:
          type: string
      required:
      - message
      - success
    ContactDeleteRequest:
      example:
        userId: userId
        email: email
      properties:
        email:
          type: string
        userId:
          type: string
      required:
      - email
      - userId
    ContactDeleteResponse:
      example:
        success: true
        message: message
      properties:
        success:
          type: boolean
        message:
          type: string
      required:
      - message
      - success
    ContactPropertyCreateRequest:
      example:
        name: name
        type: type
      properties:
        name:
          type: string
        type:
          type: string
      required:
      - name
      - type
    ContactPropertySuccessResponse:
      example:
        success: true
      properties:
        success:
          type: boolean
      required:
      - success
    ContactPropertyFailureResponse:
      example:
        success: true
        message: message
      properties:
        success:
          type: boolean
        message:
          type: string
      required:
      - message
      - success
    EventRequest:
      example:
        eventName: eventName
        userId: userId
        email: email
        eventProperties: "{}"
        mailingLists: "{}"
      properties:
        email:
          type: string
        userId:
          type: string
        eventName:
          type: string
        eventProperties:
          description: "An object containing event property data for the event, available\
            \ in emails sent by the event."
          type: object
        mailingLists:
          description: An object of mailing list IDs and boolean subscription statuses.
          type: object
      required:
      - eventName
    EventSuccessResponse:
      example:
        success: true
      properties:
        success:
          type: boolean
      required:
      - success
    EventFailureResponse:
      example:
        success: true
        message: message
      properties:
        success:
          type: boolean
        message:
          type: string
      required:
      - message
      - success
    TransactionalRequest:
      example:
        attachments:
        - filename: filename
          data: data
          contentType: contentType
        - filename: filename
          data: data
          contentType: contentType
        addToAudience: true
        dataVariables: "{}"
        transactionalId: transactionalId
        email: email
      properties:
        email:
          type: string
        transactionalId:
          description: The ID of the transactional email to send.
          type: string
        addToAudience:
          description: "If `true`, a contact will be created in your audience using\
            \ the `email` value (if a matching contact doesn't already exist)."
          type: boolean
        dataVariables:
          description: An object containing contact data as defined by the data variables
            added to the transactional email template.
          type: object
        attachments:
          description: A list containing file objects to be sent along with an email
            message.
          items:
            $ref: '#/components/schemas/TransactionalRequest_attachments_inner'
          type: array
      required:
      - email
      - transactionalId
    TransactionalSuccessResponse:
      example:
        success: true
      properties:
        success:
          type: boolean
      required:
      - success
    TransactionalFailureResponse:
      example:
        path: path
        success: true
        message: message
      properties:
        success:
          type: boolean
        path:
          type: string
        message:
          type: string
      required:
      - message
      - path
      - success
    TransactionalFailure2Response:
      example:
        success: true
        error:
          path: path
          message: message
      properties:
        success:
          type: boolean
        error:
          $ref: '#/components/schemas/TransactionalFailure2Response_error'
      required:
      - error
      - success
    TransactionalFailure3Response:
      example:
        success: true
        message: message
      properties:
        success:
          type: boolean
        message:
          type: string
      required:
      - message
      - success
    TransactionalEmail:
      example:
        lastUpdated: lastUpdated
        dataVariables:
        - dataVariables
        - dataVariables
        name: name
        id: id
      properties:
        id:
          type: string
        name:
          type: string
        lastUpdated:
          type: string
        dataVariables:
          items:
            description: TODO default missing array inner type to string
            type: string
          type: array
      required:
      - dataVariables
      - id
      - lastUpdated
      - name
    ContactProperty:
      example:
        label: label
        type: type
        key: key
      properties:
        key:
          type: string
        label:
          type: string
        type:
          type: string
      required:
      - key
      - label
      - type
    MailingList:
      example:
        name: name
        description: description
        isPublic: true
        id: id
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        isPublic:
          type: boolean
      required:
      - description
      - id
      - isPublic
      - name
    _api_key_get_200_response:
      example:
        teamName: teamName
        success: true
      properties:
        success:
          type: boolean
        teamName:
          description: The name of the team the API key belongs to.
          type: string
      required:
      - success
      - teamName
    _api_key_get_401_response:
      example:
        error: error
      properties:
        error:
          type: string
    _transactional_post_400_response:
      oneOf:
      - $ref: '#/components/schemas/TransactionalFailureResponse'
      - $ref: '#/components/schemas/TransactionalFailure2Response'
      - $ref: '#/components/schemas/TransactionalFailure3Response'
    TransactionalRequest_attachments_inner:
      example:
        filename: filename
        data: data
        contentType: contentType
      properties:
        filename:
          description: "The name of the file, shown in email clients."
          type: string
        contentType:
          description: The MIME type of the file.
          type: string
        data:
          description: The base64-encoded content of the file.
          type: string
      required:
      - contentType
      - data
      - filename
    TransactionalFailure2Response_error:
      example:
        path: path
        message: message
      properties:
        path:
          type: string
        message:
          type: string
  securitySchemes:
    apiKey:
      scheme: bearer
      type: http
